### ISSUE TITLE
Kahtlaselt palju html faile

### ISSUE THREAD

**Issue by YesterKo** [mattias30/Veebilehe-projekt#3]
Ahoi

Ma praegun näen, et meil on olemas pealeht, kõrvalleht1, kõrvalleht2, aga millegipärast ka jookide_liigid ja test fail?

1) Kui jookide_liigid on eraldi kõrvalleht, ss kustutame ühe kõrvallehtedest ära ma arvan

2) Mis/miks on test fail? Kas meil on vaja seda?

**Comment by mattias30** [comment]
Tsau

Jookide liigid on praegu lihtsalt nimekiri menüüdes olevatest jookidest, tegin html failis aga oleksin võinud lihtsalt tekstifaili kirja panna.
Testfaili lisasin kogemata, ma kustutan selle ära.

**Comment by YesterKo** [comment]
Oki super, aitäh sulle!
